### ISSUE TITLE
If I use idf-patches to patch the ESP-IDF, I want to know when I build traditional app, should I remove the patch? (US-98)

### ISSUE THREAD

**Issue by WangShuoran** [espressif/esp-privilege-separation#2]
I am very interested in this project. But when I see this project will change my ESP-IDF framework.
I have some concerns. I want to know if I patch the ESP-IDF my other projects which not use esp-privilege-separation will those be affected? Should I devide two ESP-IDF framework?
Those projects use esp32c3, esp32s3, esp32, etc...

**Comment by sachin0x18** [comment]
The changes only take effect if you enable `ESP_PRIVILEGE_SEPARATION_ENABLE` from the menuconfig option. So if you keep this disabled, your existing projects won't be affected by this change.
