### ISSUE TITLE
Problems when trying to use the example (US-108)

### ISSUE THREAD

**Issue by NB-player** [espressif/esp-privilege-separation#5]
First of all, thank you very much for your reply!
My test environment is an ubuntu20.04 device. After testing, I was able to successfully complete all the steps in the Get Started section of the [esp-idf v4.4.3 documentation.](https://docs.espressif.com/projects/esp-idf/en/v4.4.3/esp32/get-started/index.html#) I was able to successfully compile and flash the example program of this version onto my esp32s3. 

At this time, my esp-idf is located in /usr/esp/esp-idf

First, I cloned all the files of this project to my /usr/esp/esp-privilege-separation/ path:
`$git clone https://github.com/espressif/esp-privilege-separation/`

Then I tried to configure ESP-IDF according to the method in `esp-privilege-separation/examples/blink/README.md.` 

First, I performed the following operations:
`
$ cd /usr/esp/esp-idf
$ git checkout v4.4.3
$ git submodule update --init --recursive
$ ./install.sh
$ source ./export.sh
`

Then I went to the step "Apply patch on IDF":
`
$ cd /usr/esp/esp-idf
$ git apply -v /usr/esp/esp-privilege-separation/idf-patches/privilege-separation_support_v4.4.3.patch
`

After that, I copied the blink example in `/usr/esp/esp-privilege-separation/example` to `/usr/esp/ and tried` to modify the device:
$ cd /usr/esp/blink
$ set-target esp32s3

At this point, an error occurred:
`-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
 -- Building ESP-IDF components for target esp32s3 
CMake Error at /usr/esp/esp-idf/tools/cmake/build.cmake:201 (message): 
Failed to resolve component 'esp_priv_access'.
 Call Stack (most recent call first): 
/usr/esp/esp-idf/tools/cmake/build.cmake:227 (__build_resolve_and_add_req) 
/usr/esp/esp-idf/tools/cmake/build.cmake:507 (__build_expand_requirements) 
/usr/esp/esp-idf/tools/cmake/project.cmake:384 (idf_build_process)
 CMakeLists.txt:14 (project)`

Later, I realized that it might be because I installed the patch incorrectly. 
I deleted the esp-idf directory and re-cloned it,
then I copied all the files in the esp-privilege-separation folder to the esp-idf folder, followed the steps above to install the patch, and tried to set-target . However, I still encountered the same problem.

**Comment by sachin0x18** [comment]
Hi @NB-player,

The examples in this framework assume that they are placed inside esp-privilege-separation and they expect the required components to be present at a location relative to their own path. You can understand this by looking inside blink's [`CMakeLists.txt`](https://github.com/espressif/esp-privilege-separation/blob/master/examples/blink/CMakeLists.txt#L7).

So either you use the blink example as is or make a copy of the blink example in the same directory (i.e `/usr/esp/esp-privilege-separation/example`)

**Comment by mahavirj** [comment]
@NB-player I assume the comment above helped you to fix the issue. If not, please let me know and I will help you further. Closing the issue for now.
